### ISSUE TITLE
Version 6 Error on Shell 40.4.0

### ISSUE THREAD

**Issue by HackaN** [ionutbortis/gnome-bedtime-mode#16] opened 2021-09-23 15:21 UTC
Installed via extensions.gnome.org, error message says "entry.get_child is not a function"

**Comment by ionutbortis** [comment] 2021-09-23 17:31
Hello,

I tried unsuccessfully to replicate the issue on a Fedora 34 VM with Gnome 40.4.0...

Can you provide more details on the issue? Like running OS, which OS version?
Are you running some gnome extensions that remove/alter the top right aggregated menu/panel?

This might be the problematic code, but it would be nice to figure out why it doesn't work on your setup:
`modules/Decorator.js:`
```
const aggregateMenuFinder = (entry) => entry.get_child() === MainPanel.statusArea.aggregateMenu;
const aggregateMenuIndex = MainPanel._rightBox.get_children().findIndex(aggregateMenuFinder);
```

**Comment by HackaN** [comment] 2021-09-23 19:39
I get the same issue on both my machines (Fedora 34 Workstation and the other is Garuda Linux), both running Gnome 40.4.0. I did get the extension to work on a LiveCD of GeckoLinux earlier today... Could it perhaps be a Wayland related issue?

**Comment by HackaN** [comment] 2021-09-23 19:49
It's not Wayland-related, just tried to log into Gnome with X and the same thing happens.

The active extensions on fedora are...

::: Manually installed :::

- AppIndicator and KStatusNotifierItem Support
- Compiz alike magic lamp effect
- Compiz alike windows effect
- Dynamic Panel Transparency
- Gnome 40 UI Improvements
- Hue Lights
- OpenWeather
- User Themes

::: Built in :::

- Background Logo
- Dash to Dock
- GSConnect

**Comment by ionutbortis** [comment] 2021-09-23 20:27
I just created a fresh VM of Fedore 34 using Boxes, applied the updates and the Bedtime Mode extension works fine. I suspect there might be some interference with the way other extensions are changing the Gnome shell.

Are you having this menu on the right side in top bar?
![Screenshot from 2021-09-23 23-22-24](https://user-images.githubusercontent.com/5013697/134578699-2fb93762-8d0a-4a1e-b8a8-1441f4db68b0.png)

If not, how did you customize your shell?

**Comment by HackaN** [comment] 2021-10-03 14:39
it seems like the problem might have been something with my fedora installation. The computer has panicked a few times and I boot up to a  automatically restored desktop and when I enable the extensions again Bedtime Mode now seems to work.

**Comment by ionutbortis** [comment] 2021-10-03 14:50
Closing since it can't be reproduced any more :tada:

**Closed by ionutbortis** 2021-10-03 14:50 UTC
